cache:
  directories:
    - node_modules
notifications:
  email: false
language: node_js
node_js:
  - 10
install:
  - cd ./packages/when && npm ci
script:
  - cd ./packages/when && npm t
cache:
  directories:
  - "$HOME/.npm"